### ISSUE TITLE
Wrap genapi.dart as a barback transformer

### ISSUE THREAD

**Issue by ochafik** [google/streamy-dart#224]
It would be nice to define how to generate the API from `pubspec.yaml`, either from a local .json discovery file or from a URL:

```yaml
transformers:
  streamy:
    discovery_services: [
      "prefetched_discovery_files/auth_service.json",
      "https://www.googleapis.com/discovery/v1/apis/urlshortener/v1/rest"
    ]
```

Writing & bundling a transformer is very simple, happy to give it a go if that's a feature that makes sense to you guys :-)
